const UPSTREAM = "https://secure.runescape.com/m=hiscore_oldschool/index_lite.ws";
const DISCORD_API = "https://discord.com/api/v10";
const PRICES_API = "https://prices.runescape.wiki/api/v1/osrs";
const SESSION_COOKIE = "osrshub_session";
const STATE_COOKIE = "osrshub_oauth_state";
const CLOUD_KEYS = ["osrsflipit-profiles","osrsflipit-columns","osrsflipit-column-widths","osrsflipit-detail-tiles","osrsflipit-filters","osrsflipit-watch","osrsflipit-alerts","osrsflipit-rules","osrsflipit-mini-ge","osrsflipit-sound","osrsflipit-sound-volume","osrsflipit-sound-type","osrsflipit-theme","osrsflipit-chart-layers","osrsflipit-recipe-favs","osrsflipit-flip-log","osrsflipit-bankroll","osrsflipit-portfolio","osrshub-dashboard-pins","osrshub-account"];
function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json; charset=utf-8",...headers}})}
function cookies(request){const raw=request.headers.get("Cookie")||"";return Object.fromEntries(raw.split(";").map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf("=");return [x.slice(0,i),decodeURIComponent(x.slice(i+1))]}))}
function cookie(name,value,maxAge){return `${name}=${encodeURIComponent(value)}; Max-Age=${maxAge}; Path=/; HttpOnly; Secure; SameSite=Lax`}
function redirect(url,headers={}){return new Response(null,{status:302,headers:{Location:url,...headers}})}
function b64u(bytes){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function ub64(s){s=s.replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function sign(secret,text){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return new Uint8Array(await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(text)))}
async function validSig(secret,text,sig){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["verify"]);try{return await crypto.subtle.verify("HMAC",key,ub64(sig),new TextEncoder().encode(text))}catch{return false}}
function authConfigured(env){return !!(env.DB&&env.DISCORD_CLIENT_ID&&env.DISCORD_CLIENT_SECRET&&env.DISCORD_REDIRECT_URI&&env.OSRSHUB_AUTH_SECRET)}
function botConfigured(env){return !!env.DISCORD_BOT_TOKEN}
async function readUserData(env,userId){const row=await env.DB.prepare("SELECT data_json FROM user_data WHERE user_id=?1").bind(userId).first();if(!row?.data_json)return {};try{const d=JSON.parse(row.data_json);return d&&typeof d==="object"&&!Array.isArray(d)?d:{}}catch{return {}}}
async function writeUserData(env,userId,data){const raw=JSON.stringify(data||{});if(raw.length>900000)throw new Error("Saved data is too large to sync.");const now=Date.now();await env.DB.prepare("INSERT INTO user_data(user_id,data_json,updated_at) VALUES(?1,?2,?3) ON CONFLICT(user_id) DO UPDATE SET data_json=excluded.data_json,updated_at=excluded.updated_at").bind(userId,raw,now).run();return now}
async function discordBotRequest(env,path,options={}){if(!botConfigured(env))throw new Error("Discord bot integration is not configured.");const res=await fetch(`${DISCORD_API}${path}`,{...options,headers:{Authorization:`Bot ${env.DISCORD_BOT_TOKEN}`,"Content-Type":"application/json",...(options.headers||{})}});const text=await res.text();let body=null;try{body=JSON.parse(text)}catch{}if(!res.ok)throw new Error(body?.message||`Discord API returned ${res.status}`);return body}
async function sendDiscordDM(env,userId,payload){const channel=await discordBotRequest(env,"/users/@me/channels",{method:"POST",body:JSON.stringify({recipient_id:String(userId)})});if(!channel?.id)throw new Error("Discord did not return a DM channel.");await discordBotRequest(env,`/channels/${channel.id}/messages`,{method:"POST",body:JSON.stringify(payload)});return channel.id}
async function sendDiscordAlert(env,userId,a){const itemUrl=`${env.PUBLIC_ORIGIN||""}/?item=${encodeURIComponent(a.itemId)}`;return sendDiscordDM(env,userId,{embeds:[{title:`${a.name} alert triggered`,description:`**${a.metric}** ${a.metric==="roi"?"is":"reached"} **${a.metric==="roi"?Number(a.target).toFixed(2)+"%":Math.round(a.target).toLocaleString("en-GB")+" gp"}**`,color:0x8b5cf6,fields:[{name:"Current value",value:a.metric==="roi"?`${Number(a.value).toFixed(2)}%`:`${Math.round(a.value).toLocaleString("en-GB")} gp`,inline:true},{name:"Condition",value:`${a.direction||"threshold"}`,inline:true},{name:"Item",value:a.name,inline:true}],footer:{text:"OSRS Hub · Discord alerts"},timestamp:new Date(a.at).toISOString(),url:itemUrl||undefined,thumbnail:a.icon?{url:`https://prices.runescape.wiki/osrs/item/${a.itemId}/icon`}:undefined}]});}
async function currentUser(request,env){if(!authConfigured(env))return null;const c=cookies(request)[SESSION_COOKIE];if(!c)return null;const [uid,exp,sig]=c.split(".");if(!uid||!exp||!sig||Number(exp)<Date.now()||!(await validSig(env.OSRSHUB_AUTH_SECRET,`${uid}.${exp}`,sig)))return null;return env.DB.prepare("SELECT id,username,global_name,avatar FROM users WHERE id=?1").bind(uid).first()}
async function auth(request,env){const url=new URL(request.url);if(!authConfigured(env)){return url.pathname==="/api/auth/me"?json({user:null,data:null,configured:false}):json({error:"Discord login is not configured yet."},503)}
 if(request.method==="GET"&&url.pathname==="/api/auth/discord"){const state=b64u(crypto.getRandomValues(new Uint8Array(24)));const u=new URL(`${DISCORD_API}/oauth2/authorize`);u.searchParams.set("client_id",env.DISCORD_CLIENT_ID);u.searchParams.set("redirect_uri",env.DISCORD_REDIRECT_URI);u.searchParams.set("response_type","code");u.searchParams.set("scope","identify");u.searchParams.set("state",state);return redirect(u.toString(),{"Set-Cookie":cookie(STATE_COOKIE,state,600)})}
 if(request.method==="GET"&&url.pathname==="/api/auth/callback"){const c=cookies(request),code=url.searchParams.get("code"),state=url.searchParams.get("state");if(!code||!state||state!==c[STATE_COOKIE])return redirect(`${url.origin}/?discord=error`);try{const tokenRes=await fetch(`${DISCORD_API}/oauth2/token`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:env.DISCORD_CLIENT_ID,client_secret:env.DISCORD_CLIENT_SECRET,grant_type:"authorization_code",code,redirect_uri:env.DISCORD_REDIRECT_URI})});const token=await tokenRes.json();if(!tokenRes.ok||!token.access_token)throw new Error("Discord token exchange failed");const userRes=await fetch(`${DISCORD_API}/users/@me`,{headers:{Authorization:`Bearer ${token.access_token}`}});const user=await userRes.json();if(!userRes.ok||!user.id)throw new Error("Discord identity lookup failed");const now=Date.now();await env.DB.prepare("INSERT INTO users(id,username,global_name,avatar,created_at,updated_at) VALUES(?1,?2,?3,?4,?5,?6) ON CONFLICT(id) DO UPDATE SET username=excluded.username,global_name=excluded.global_name,avatar=excluded.avatar,updated_at=excluded.updated_at").bind(user.id,user.username||"",user.global_name||"",user.avatar||null,now,now).run();const exp=now+30*24*60*60*1000,base=`${user.id}.${exp}`,sig=b64u(await sign(env.OSRSHUB_AUTH_SECRET,base)),r=redirect(`${url.origin}/?discord=connected`);r.headers.append("Set-Cookie",cookie(SESSION_COOKIE,`${user.id}.${exp}.${sig}`,30*24*60*60));r.headers.append("Set-Cookie",cookie(STATE_COOKIE,"",0));return r}catch(e){console.error("Discord OAuth",e);return redirect(`${url.origin}/?discord=error`)}}
 if(request.method==="GET"&&url.pathname==="/api/auth/me"){const user=await currentUser(request,env);if(!user)return json({user:null,data:null});const row=await env.DB.prepare("SELECT data_json FROM user_data WHERE user_id=?1").bind(user.id).first();let data=null;try{data=row?.data_json?JSON.parse(row.data_json):null}catch{}return json({user,data})}
 if(request.method==="POST"&&url.pathname==="/api/auth/sync"){const user=await currentUser(request,env);if(!user)return json({error:"Not signed in."},401);const body=await request.json().catch(()=>null),incoming=body?.data;if(!incoming||typeof incoming!=="object"||Array.isArray(incoming))return json({error:"Invalid sync payload."},400);const existing=await readUserData(env,user.id);const data={...incoming};if(existing.osrshubDiscord)data.osrshubDiscord=existing.osrshubDiscord;const raw=JSON.stringify(data);if(raw.length>900000)return json({error:"Saved data is too large to sync."},413);const now=Date.now();await env.DB.prepare("INSERT INTO user_data(user_id,data_json,updated_at) VALUES(?1,?2,?3) ON CONFLICT(user_id) DO UPDATE SET data_json=excluded.data_json,updated_at=excluded.updated_at").bind(user.id,raw,now).run();return json({ok:true,updatedAt:now})}
 if(request.method==="POST"&&url.pathname==="/api/auth/logout")return json({ok:true},200,{"Set-Cookie":cookie(SESSION_COOKIE,"",0)});
 return json({error:"Not found"},404)}
async function discordIntegration(request,env){
 const user=await currentUser(request,env);if(!user)return json({error:"Not signed in."},401);
 if(request.method==="GET"&&new URL(request.url).pathname==="/api/discord/status"){const data=await readUserData(env,user.id),d=data.osrshubDiscord||{};return json({connected:!!d.connected,frequency:d.frequency||"instant",lastConnectedAt:d.lastConnectedAt||null,installUrl:`https://discord.com/oauth2/authorize?client_id=${encodeURIComponent(env.DISCORD_CLIENT_ID)}&integration_type=1&scope=applications.commands`})}
 if(!botConfigured(env))return json({error:"Discord bot notifications are not configured on this Worker yet. Add DISCORD_BOT_TOKEN as a Worker secret."},503);
 if(request.method==="POST"&&new URL(request.url).pathname==="/api/discord/connect"){try{const data=await readUserData(env,user.id),body=await request.json().catch(()=>({})),frequency=["instant","5m","15m","30m","1h"].includes(body?.frequency)?body.frequency:"instant";const channelId=await sendDiscordDM(env,user.id,{content:`OSRS Hub Discord alerts are connected, ${user.global_name||user.username}. Your saved OSRS Hub price alerts can now notify you here. You can change notification frequency from the Alerts page.`});data.osrshubDiscord={connected:true,channelId,frequency,lastConnectedAt:Date.now(),nextAllowedAt:0,delivery:"dm"};await writeUserData(env,user.id,data);return json({ok:true,connected:true,frequency,delivery:"dm"})}catch(e){const msg=e?.message||"Could not open a Discord DM with this account.";return json({error:`${msg} If you have not installed OSRSHub to your Discord account yet, use the Add OSRSHub to Discord button first, then try Connect again.`},502)}}
 if(request.method==="POST"&&new URL(request.url).pathname==="/api/discord/test"){try{const data=await readUserData(env,user.id),d=data.osrshubDiscord;if(!d?.connected)return json({error:"Connect Discord alerts first."},400);await sendDiscordDM(env,user.id,{embeds:[{title:"OSRS Hub Discord alerts are working",description:"This is a test notification from your signed-in OSRS Hub account.",color:0x8b5cf6,footer:{text:"OSRS Hub · test notification"},timestamp:new Date().toISOString()}]});return json({ok:true})}catch(e){return json({error:e?.message||"Discord test failed."},502)}}
 if(request.method==="POST"&&new URL(request.url).pathname==="/api/discord/settings"){const body=await request.json().catch(()=>({})),frequency=["instant","5m","15m","30m","1h"].includes(body?.frequency)?body.frequency:"instant";const data=await readUserData(env,user.id),d=data.osrshubDiscord||{};if(!d.connected)return json({error:"Connect Discord alerts first."},400);data.osrshubDiscord={...d,frequency};await writeUserData(env,user.id,data);return json({ok:true,frequency})}
 if(request.method==="POST"&&new URL(request.url).pathname==="/api/discord/disconnect"){const data=await readUserData(env,user.id);delete data.osrshubDiscord;await writeUserData(env,user.id,data);return json({ok:true})}
 return json({error:"Not found"},404)}
async function runDiscordAlertCron(env){
 if(!env.DB||!botConfigured(env))return;
 try{
  const latestRes=await fetch(`${PRICES_API}/latest`,{cf:{cacheTtl:45,cacheEverything:true}});if(!latestRes.ok)return;
  const latest=await latestRes.json(),rows=latest.data||{};
  const users=await env.DB.prepare("SELECT user_id,data_json FROM user_data WHERE data_json LIKE '%osrshubDiscord%'").all();
  for(const row of users.results||[]){
   let data;try{data=JSON.parse(row.data_json)}catch{continue}
   const d=data.osrshubDiscord;if(!d?.connected||!d.channelId)continue;
   const rules=Array.isArray(data["osrshubflipit-rules"])?data["osrshubflipit-rules"]:[];if(!rules.length)continue;
   const state={...(d.ruleState||{})};let stateChanged=false;const fresh=[];
   for(const rule of rules){
    const raw=rows[String(rule.id)]||rows[rule.id];if(!raw)continue;
    const buy=Number(raw.high||0),sell=Number(raw.low||0),tax=Math.min(Math.floor(sell*.02),5000000),margin=buy>0&&sell>0?buy-sell-tax:0,roi=buy?margin/buy*100:0;
    const value=rule.metric==="buy"?buy:rule.metric==="sell"?sell:rule.metric==="margin"?margin:roi;
    const hit=rule.direction==="above"?value>=Number(rule.value):value<=Number(rule.value);
    const armed=state[rule.id]?.armed!==false;
    if(hit&&armed){fresh.push({id:crypto.randomUUID(),ruleId:rule.id,itemId:rule.id,name:String(rule.name||"OSRS item"),metric:rule.metric,value,target:Number(rule.value),direction:rule.direction,at:Date.now()});state[rule.id]={armed:false,lastTriggered:Date.now()};stateChanged=true}
    else if(!hit&&!armed){state[rule.id]={...state[rule.id],armed:true};stateChanged=true}
   }
   const cooldown={instant:0,"5m":300000,"15m":900000,"30m":1800000,"1h":3600000}[d.frequency||"instant"]||0;
   const now=Date.now();
   if(fresh.length && Number(d.nextAllowedAt||0)<=now){
    for(const a of fresh){try{await sendDiscordDM(env,row.user_id,{embeds:[{title:`${a.name} alert triggered`,description:`**${a.metric}** ${a.metric==="roi"?"is":"reached"} **${a.metric==="roi"?Number(a.target).toFixed(2)+"%":Math.round(a.target).toLocaleString("en-GB")+" gp"}**`,color:0x8b5cf6,fields:[{name:"Current value",value:a.metric==="roi"?`${Number(a.value).toFixed(2)}%`:`${Math.round(a.value).toLocaleString("en-GB")} gp`,inline:true},{name:"Condition",value:`${a.direction||"threshold"}`,inline:true},{name:"Item",value:a.name,inline:true}],footer:{text:"OSRS Hub · live GE alert"},timestamp:new Date(a.at).toISOString()}]})}catch(e){console.warn("Discord DM failed",row.user_id,e?.message)}}
    d.nextAllowedAt=cooldown?now+cooldown:0;
   }
   if(stateChanged||fresh.length){data.osrshubDiscord={...d,ruleState:state};await writeUserData(env,row.user_id,data)}
  }
 }catch(e){console.warn("Discord alert cron failed",e?.message)}
}
export default {async fetch(request,env){const url=new URL(request.url);if(url.pathname.startsWith("/api/auth/"))return auth(request,env);if(url.pathname.startsWith("/api/discord/"))return discordIntegration(request,env);if(request.method==="OPTIONS"&&url.pathname==="/api/hiscores")return new Response(null,{status:204,headers:{"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET, OPTIONS","Access-Control-Allow-Headers":"Content-Type"}});if(request.method==="GET"&&url.pathname==="/api/hiscores")return hiscores(request);return env.ASSETS.fetch(request)},async scheduled(event,env,ctx){ctx.waitUntil(runDiscordAlertCron(env))}};
